### ISSUE TITLE
关于parkingos_cloud_web无法部署的问题

### ISSUE THREAD

**Issue by CoderIvan** [ParkingOS/ParkingOS_cloud#8]
您好，最近正在尝试部署这个项目

这个parkingos_cloud_web在文档中并没详细的说明应该如何部署

能麻烦指教一下吗？

**Comment by CoderIvan** [comment]
已经成功部署了

**Comment by zzlxf** [comment]
你好， 能指导下怎么部署的吗？629938044@qq.com,谢谢。
